apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-regs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-regs
    app.kubernetes.io/part-of: tkrw-pr712-0075-0009-app
  name: devfile-sample-regs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-regs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-regs
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-regs@sha256:e077355bc0396a022e45493d8ed408342a34c08b2cb46aa5005bb7ab042a82e1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
